
#@username = "Wagner"
###
GET localhost:8080/users

###
POST localhost:8080/users
Content-Type: application/json

{
    "username": "Wagner",
    "password": "123",
    "email": "wagner@thinkr.com"
}

###
POST localhost:8080/tasks
Content-Type: application/json
Authorization: Basic Wagner 123

{
  "description": "New task",
  "title": "Test task",
  "priority": "low",
  "startedAt": "2023-11-11T00:00:00Z",
  "finishedAt": "2023-11-12T00:00:00Z"
}

###
GET localhost:8080/tasks
Content-Type: application/json
Authorization: Basic Wagner 123

###
PATCH localhost:8080/tasks/3b5b564c-f6f4-4e3c-9e6b-9f2b2ee417e7
Content-Type: application/json
Authorization: Basic Wagner 123

{
  "description": "New title updated",
  "title": "Updated task",
  "priority": "high"
}
